### ISSUE TITLE
Conventional Commits

### ISSUE THREAD

**Issue by thclark** [octue/pre-commit-hooks#1]
### Use Case

We want to be able to use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) in our projects to reduce the chore burden of creating releases.

### Current state

We have a release workflow that's based on release/x.y.z branches, and automatically creates tagged releases on successful merge of a PR. It works pretty well but has the following flaws:

- We manually have to track any breaking changes and decide on version ourselves. We're a bit fast and loose with breaking things, to be honest.
- Where we make a PR `feature/issue-whatever -> release/x.y.z`, we have to manually copy the contents of the PR notes across into the relevant sections PR `release/x.y.z -> main`
- In this release flow, the release numbers are determined *a-priori*. However, the correct release number is a function of the contents of the release. Adding a single change therefore means constructing a release branch with a new version number, and corresponding with colleagues to make sure nobody's about to release something semver-earlier than that. **It's a grind**, and violates the core principle of CD, because it tends us to group new features together into a release branch instead of getting them out of the door quickly.
  - With twined and octue-sdk, releases are fairly well controlled and planned. We know what's going into them. However, in `amy` and `windquest` (applications, rather than libraries), development is much less structured so the release flow is really painful. Also, because there's a 'staging' step of manual QC before an application goes out of the door, there's an extra grind of copying all the release notes through the staging branch and manually creating a release once they hit main.
  
### Proposed solution

Develop four tools ([the following list of conventional commit plugins will be helpful](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#projects-using-conventional-commits))...

- [x] **DO FIRST, get this deployed across all repos** Implement a pre-commit hook in this repository to enforce commit message patterns. Can be inspired by [this](https://github.com/thclark/pre-commit-sphinx) and/or follow the guide at [pre-commit.com](https://pre-commit.com).
- [x] **DO SECOND** Implement a GHA, that can be run on pull requests to check that the version (e.g. in `package.json` is correct) and, optionally, update and commit the correct value automatically (can use, for example, [this tool](https://github.com/idc101/git-mkver))
- [x] **DO THIRD** Find or implement a GHA that can be run on PRs to update their Notes with sections on new features, breaking changes and minor fixes **automatically from the commit contents**
- [x] **DO FOURTH** Find or implement a GHA that can be run on merge of code into `main` to create an automated release from the PR notes. We already have this, but it might need tweaking - it currently checks the version against the `release/x.y.z` branch name. It needs to check the version against the calculated value instead.

**Comment by thclark** [comment]
@cortadocodes I've assigned this to you, we'll come to it fairly soon I think, as the more I think about it, the more it's really going to make a difference to workflow.

**Comment by cortadocodes** [comment]
I've had a look at the `conform` tool written in `go` which gives some useful features for this:
* Enforces header of given length in the imperative with an ending that isn't invalid (e.g. a full stop)
* Allows enforcing (or not) of the presence of a body
* Spell checks the commit message in the given language
* Allows a discrete set of custom commit codes (e.g. the ones I've already been using)

For me currently, it works if a pre-built release is downloaded and manually added as a hook in the `.git` directory, but it doesn't seem to work properly with
* `go get` 
* `go build`
* The provided GitHub action
* The provided `pre-commit` hook

So I think it may be better to write our own, but I'm wondering which of the features above are must haves and which are could haves @thclark?

**Comment by cortadocodes** [comment]
It seems to me like these are the must-haves:
- [ ] Enforces Conventional Commits
- [ ] Enforces header of given length
- [ ] Enforces header with an ending that isn't invalid
- [ ] Allows a discrete set of custom commit codes

**Comment by thclark** [comment]
> So I think it may be better to write our own,

Our own what? Conform tool? Or GHA and pre-commit hook to run the existing conform tool? The latter, yes - the former would very much raise an eyebrow at how far deep we're getting.

> It seems to me like these are the must-haves:
> * [ ]  Enforces Conventional Commits
> * [ ]  Enforces header of given length
> * [ ]  Enforces header with an ending that isn't invalid
> * [ ]  Allows a discrete set of custom commit codes

I agree that skipping the spell checker is sensible. It's mildly annoying when there are typos, it's a crashing marshmallowman on your dev flow when the spell checker doesn't have your word or the thing you deliberately want to type.

It seems like you've intentionally missed the imperative tense constraint on the header *(e.g: enforcing the form between "fixes the issue" (passive) "fix the issue" (imperative))*. Why is that? Anything to add to the pros and cons below? 

Pros: 
 - Automated releases will read strangely if the tenses are mixed
Cons:
 - it may cause too much friction as we adopt the tool (and have our developers adopt it)
 - Similar logic might apply as for the spellchecker (too constraining when you really are wanting to type a specific message).

**Comment by cortadocodes** [comment]
I meant writing our own `conform` tool, pre-commit package, and GHA. I've started doing it and it's turnint out to be quite simple - I'm nearly done!

Agree about spell checker - that's why I left it out.

With the imperative, I think all commits should be in the imperative but I'm aware that not everybody wants to do that. I also didn't know how to easily check if a sentence is in the imperative without NLP, although [it looks like `conform` just checks if the first word in the header after the commit code is in a list of known imperative verbs](https://github.com/talos-systems/conform/blob/master/internal/policy/commit/check_imperative_verb.go).

I do think it's part of good practice to make commits imperative, so I could/should probably easily add what `conform` has.

**Comment by thclark** [comment]
@cortadocodes if you're building a small equivalent of the conform tool, plus a pre-commit hook, perhaps we'll group them in this repo and rename the repo (eg `pre-commit-conventional-commit`), rather than having the tool in a separate repo, and the hook in this one.

**Comment by thclark** [comment]
> ~~@cortadocodes if you're building a small equivalent of the conform tool, plus a pre-commit hook, perhaps we'll group them in this repo and rename the repo (eg `pre-commit-conventional-commit`), rather than having the tool in a separate repo, and the hook in this one.~~

Probably scratch that last, I didn't realise how small the checker would be.

**Comment by cortadocodes** [comment]
This is now released in https://github.com/octue/octue-sdk-python/releases/tag/0.1.20

The only difference from the issue description is that we agreed to only *check* if the `setup.py` version is semantically correct rather than actually updating it - this allows us complete control over the version number of the next release in case we need to override what `git-mkver` says.

**Comment by cortadocodes** [comment]
This has now also been rolled out to `amy`, `twined`, and `planex-site`.
